name: frog_auth
description: Authentication for Dart Frog apps
version: 0.0.2
repository: https://github.com/ptrbrynt/frog_auth

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dart_frog: ^0.1.0

dev_dependencies:
  mocktail: ^0.3.0
  netsells_flutter_analysis: ^3.0.0
  test: ^1.16.0
